### ISSUE TITLE
Nicotine substance page isn't working

### ISSUE THREAD

**Issue by miglsoares** [dlbnco/tripby.org#88]
# Bug report

## Describe the bug
Nicotine substance page isn't working. It seems like something from api.

## To Reproduce
Go to `/substance/Nicotine` and look at the console.

## Screenshots
![image](https://user-images.githubusercontent.com/20358128/90214302-68d4cf00-ddce-11ea-8740-7d1c55ea824c.png)

![image](https://user-images.githubusercontent.com/20358128/90214342-8e61d880-ddce-11ea-87e5-1d2b0cdc4c5d.png)

## System information

- Firefox 79.0
- OS: Ubuntu 20.04

**Comment by dlbnco** [comment]
Looks like an issue from the PsychonautWiki API, indeed. It's not uncommon for that to happen, but they frequently fix these kinds of things.

However, there is also an issue with error handling. It should not crash but rather show the error state. I just opened a PR to fix that: https://github.com/dlbnco/tripby.org/pull/89
